language: node_js

sudo: required

node_js:
  - 8.9.4

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo
 
before_install:
  - npm install -g hexo-cli

install:
  - npm install

before_script:
  - npm install -g gulp

script:
  - hexo clean
  - hexo generate
  - gulp build
  - hexo qiniu sync

after_script:
  - git config user.name "JiongZhu"
  - git config user.email "zhxyimm@sina.cn"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - sed -i "s/cg_token/${CG_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
